specVersion: 0.0.1
description: ''
repository: ''
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/ws?apikey=cb6c9187-43a3-4e33-b5ff-80fd1bc48b30
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7560558
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
      #handlers:
      #  - handler: handleTransfer
      #    kind: substrate/EventHandler
      #    filter:
      #      module: balances
      #      method: Transfer
